Random Forest

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
wines = pd.read_csv("wines.csv")

In [23]:
wines.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

Hacer las predicciones de los tipos de vinos en función de su características

In [24]:
#Separar las características (columnas)
X = wines.drop('Wine Type', axis = 1) #axis = 1 para decir que es una columna
y = wines['Wine Type']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
#Separa el dataset en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Entrenar el modelo y hacer las predicciones

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
randomforest = RandomForestClassifier(n_estimators=80) #Hay que pasarle el número de estimadores, el número de árboles que va hacer para estimar el resultado

In [29]:
#Una vez creado el random forest, se entrena con los datos de entrenamiento y los valores objetivos de entrenamiento
randomforest.fit(X_train, y_train) 

RandomForestClassifier(n_estimators=80)

In [30]:
predictions = randomforest.predict(X_test)

In [31]:
#Predicciones para esos datos
predictions

array(['Two', 'Three', 'Three', 'Two', 'One', 'Three', 'Two', 'Two',
       'Two', 'Three', 'Three', 'Two', 'One', 'One', 'Three', 'Three',
       'One', 'Three', 'Two', 'Two', 'One', 'Three', 'Two', 'Three',
       'Three', 'Two', 'Two', 'Two', 'Two', 'Two', 'Three', 'One', 'Two',
       'Three', 'One', 'Two', 'Two', 'One', 'Three', 'Two', 'Three',
       'One', 'Two', 'One', 'One', 'Three', 'Two', 'One', 'Three', 'One',
       'One', 'One', 'One', 'Two'], dtype=object)

In [36]:
y_test.head(10) #Coinciden los primeros valores con las predicciones

69       Two
166    Three
143    Three
84       Two
57       One
170    Three
71       Two
70       Two
76       Two
136    Three
Name: Wine Type, dtype: object

Evaluar el modelo para ver la precisión que tiene

In [33]:
from sklearn.metrics import classification_report, confusion_matrix

In [34]:
#Mostrar la precisión del modelo, que es muy alta. Funciona mejor el random forest que los árboles de decisión para este dataset de vinos
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         One       1.00      1.00      1.00        16
       Three       1.00      1.00      1.00        17
         Two       1.00      1.00      1.00        21

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [39]:
print(confusion_matrix(y_test, predictions)) #La mayor parte son positivos correctos

[[16  0  0]
 [ 0 17  0]
 [ 0  0 21]]
