Arboles de decisión - Es un método de clasificación

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
wines_dt = pd.read_csv("wines.csv")

In [5]:
wines_dt.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [6]:
wines_dt['Wine Type'].unique() #Ver los valores únicos de la columna

array(['One', 'Two', 'Three'], dtype=object)

In [7]:
wines_dt['Wine Type'].value_counts() #Ver el número de vinos de cada tipo

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [9]:
X = wines_dt.drop("Wine Type", axis = 1) #Quitar la columna Wine Type. #Características  

In [14]:
y = wines_dt["Wine Type"] #Valor objetivo

In [15]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Entrenar el modelo y predecir las variables, hacer las predicciones

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
tree = DecisionTreeClassifier()

In [48]:
tree.fit(X_train, y_train) #Entrenar la variable tree se entrena con los datos de entrenamiento

DecisionTreeClassifier()

Una vez entrenado ya puedo crear mis propias predicciones

In [49]:
predictions = tree.predict(X_test) #Va predecir el tipo de vinos

In [50]:
predictions

array(['Three', 'Three', 'Two', 'Two', 'One', 'Two', 'One', 'One', 'Two',
       'Two', 'Three', 'Three', 'One', 'Two', 'One', 'Two', 'One',
       'Three', 'Two', 'One', 'Two', 'Three', 'Three', 'Two', 'One',
       'One', 'One', 'Three', 'Three', 'Two', 'Two', 'Three', 'Two',
       'Three', 'One', 'One', 'Two', 'Three', 'One', 'One', 'One', 'Two',
       'One', 'Three', 'Three', 'One', 'Three', 'Two', 'Three', 'Two',
       'One', 'Two', 'Three', 'Three'], dtype=object)

In [51]:
y_test.head(10)

163    Three
174    Three
93       Two
69       Two
53       One
115      Two
26       One
2        One
72       Two
129      Two
Name: Wine Type, dtype: object

Evaluar el modelo

In [52]:
from sklearn.metrics import classification_report, confusion_matrix

In [58]:
print(classification_report(y_test, predictions)) #Se le pasa las soluciones (y_test) que son los tipos de vinos de los datos de test y las prediciones para evaluar el modelo

              precision    recall  f1-score   support

         One       0.89      1.00      0.94        16
       Three       0.94      0.94      0.94        18
         Two       0.94      0.85      0.89        20

    accuracy                           0.93        54
   macro avg       0.93      0.93      0.93        54
weighted avg       0.93      0.93      0.93        54



In [60]:
print(confusion_matrix(y_test, predictions)) #Les paso los mismo parámetros. Positivos correctos están en diagonal (16,17,17).

[[16  0  0]
 [ 0 17  1]
 [ 2  1 17]]
