In [2]:
#Números aleatorios
import numpy as np

In [4]:
np.random.rand(5) #Array de números random

array([0.81265075, 0.87567045, 0.20093499, 0.52216943, 0.42681654])

In [83]:
np.random.rand(5,4) #Array de 2 dimensiones, 5 filas y 4 columnas

array([[0.94900556, 0.52973098, 0.11612222, 0.1604411 ],
       [0.75016044, 0.4202769 , 0.13089576, 0.52680202],
       [0.22838324, 0.22381858, 0.86485029, 0.1412459 ],
       [0.3614937 , 0.54039795, 0.74875481, 0.40265824],
       [0.15133367, 0.03167348, 0.77338114, 0.67666105]])

In [7]:
np.random.randn(4) #Array de números random con distribución normal positivos y negativos

array([-0.56117833, -0.24845789,  0.43285035, -0.35133144])

In [8]:
np.random.randn(4,5)

array([[ 1.50451508,  0.43641699, -0.91755718,  0.55015504, -0.16154936],
       [-0.32434867, -1.25072013,  0.53105505, -0.72997321, -0.61138763],
       [ 0.02067149,  0.8562108 , -0.21991999,  0.41548465,  1.06500299],
       [ 2.51903625, -0.6715078 ,  0.13547408,  1.19748203, -2.13590109]])

In [16]:
np.random.randint(1,19) #Array de números enteros random. Genera un número random entre 1 y 19

5

In [20]:
np.random.randint(1,20,5) #El tercer parámetro es para la cantidad de números a devolver

array([17,  6, 13, 10, 15])

In [22]:
#Cambiar tamaño de los arrays

In [32]:
array = np.random.randint(1,75,21)

In [88]:
array

array([11, 53, 67, 54, 34,  7, 37, 29,  1, 19, 50, 69, 39, 13, 15, 14, 72,
       37, 38, 19, 44])

In [34]:
matriz = array.reshape(7,3) #Decirle el número de filas y columnas que queremos, de acuerdo a los datos que devuelve

In [35]:
matriz

array([[11, 53, 67],
       [54, 34,  7],
       [37, 29,  1],
       [19, 50, 69],
       [39, 13, 15],
       [14, 72, 37],
       [38, 19, 44]])

In [36]:
#Valores máximos y minimoss

In [74]:
array_ = np.random.randint(1,100,50)
array_

array([75, 59, 78, 24, 37, 17,  8,  3, 75, 21, 43, 75, 48, 66, 17, 74, 39,
        5, 56, 55, 18, 33, 76, 93, 22,  9, 40, 28, 69, 16, 94, 87, 57, 28,
        3, 80, 46, 86, 86, 46, 98, 21, 49, 88, 57, 34, 60, 67,  1, 26])

In [75]:
max_value = array_.max() #Sacar el valor máximo
max_value

98

In [76]:
max_value_position = array_.argmax() #Devolver la posición del valor máximo
max_value_position

40

In [77]:
min_value = array_.min() #Sacar el valor mínimo
min_value

1

In [78]:
min_value_position = array_.argmin() #Devolver la posición del valor minímo
min_value_position

48