In [1]:
#Indexación en arrays
import numpy as np

In [2]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array[-4]

6

In [10]:
array[2:4] #Seleccionar varias posiciónes

array([2, 3])

In [11]:
array[:] #Seleccioanr todo el array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array[5:] #Seleccionar desde la posición 5 hasta el final

array([5, 6, 7, 8, 9])

In [14]:
array[:4] #Seleccionar desde la posición 0 hasta la 4

array([0, 1, 2, 3])

In [25]:
array2 = array.copy() #Copia del array
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Array con 2 dimensiones

In [29]:
array_ = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array_[0] #Seleccionar una fila

array([1, 2, 3])

In [32]:
array_[:2] #Seleccionar las primeras 2 filas

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
array_[2][1] #Seleccionar tercera fila y 2 columna

8

In [82]:
array_[2,0] #Seleccionar tercera fila y primera columna

7

In [79]:
array_[:,:2] #Seleccionar todas las filas y las 2 primeras columnas en la posición 1

array([[1, 2],
       [4, 5],
       [7, 8]])