In [1]:
#Seleccionar elementos de un array según una condición
import numpy as np

In [13]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
condition = array >= 5 #Seleccionar los elementos del array que son mayores que 5
condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
array[condition] #Ver los elementos seleccionados

array([5, 6, 7, 8, 9])

In [21]:
array_updated = array[condition]
array_updated

array([5, 6, 7, 8, 9])

In [22]:
array[array > 6] #Forma más rápida

array([7, 8, 9])

In [28]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

In [29]:
#Operaciones con arrays

In [30]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
array * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [42]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
array * array2

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [ ]:
#Ejecutar funciones sobre los ararys con la libreria numpy

In [59]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [62]:
np.max(array2)

14