In [72]:
#Exercises
import numpy as np

In [73]:
#Exercise 1
array = numpy.arange(10,40)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [74]:
min_value = array.min()
min_value

10

In [75]:
max_value = array.max()
max_value

39

In [76]:
matriz = array.reshape(3, 10)
matriz

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [77]:
array_selection = matriz[0,9] #Seleccionar el valor superior derecho de la matriz. Otra forma es matriz[0][9]
array_selection

19

In [78]:
#Exercise 2
array2 = np.random.randint(0,100,9)
array2

array([85, 25,  9, 91, 42, 77, 90, 14, 76])

In [79]:
matriz2 = array2.reshape(3,3)
matriz2

array([[85, 25,  9],
       [91, 42, 77],
       [90, 14, 76]])

In [84]:
matriz2[2][2] #Seleccionar el valor inferior derecho de la matriz

76