In [1]:
#Numpy arrays - arange, zeros, ones, linspace, eye

In [2]:
import numpy as np

In [3]:
array = np.arange(5) #Agregar 5 valores al arreglo

In [4]:
array

array([0, 1, 2, 3, 4])

In [5]:
np.arange(2,10) #Agregar indicando incio y fin

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,10,2) #Se pasa el tercer parámetro para que vaya de 2 en 2

array([2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(5,8,20) #Genera 20 elementos entre el 5 y el 8

array([5.        , 5.15789474, 5.31578947, 5.47368421, 5.63157895,
       5.78947368, 5.94736842, 6.10526316, 6.26315789, 6.42105263,
       6.57894737, 6.73684211, 6.89473684, 7.05263158, 7.21052632,
       7.36842105, 7.52631579, 7.68421053, 7.84210526, 8.        ])

In [20]:
np.eye(5) #Genera una matriz de 2 dimensiones de 5 filas y 5 columnas.Rellena con 0 menos la vertical que llena de 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])